namespace: josesolis2201
name: metabase
version: 0.0.1
readme: README.md
authors:
  - Jose Solis <josesolisrosales@gmail.com>

description: Ansible modules for metabase administration
license:
  - MIT

tags:
  - metabase

repository: https://github.com/josesolis2201/rancher-metabase-modules
issues: https://github.com/josesolis2201/rancher-metabase-modules/issues

